pipeline {
    agent any
        stages{
            stage ( 'TEST1' ) {
		        
					    steps { 
						    
						    
						    when {
                                                 branch 'master' 
                                                       }
						    sh '''
							   echo "this is executed from TEST1 stage and branch is master"
							   cat README.md
				               '''
							  }
							}
            stage ( 'TEST2' ) {
		         steps {
				  when {
			        branch 'master'
				    }           
				 
				 sh '''
				   echo " this is executed from TEST2 stage and branch is master "
				    cat README.md  
				   '''
                            }
			}
                    } 
		}
