pipeline {
	agent { label 'master' }
        stages{
            stage ( 'TEST1' ) {
		        
					    steps { 
						    sh '''
							   echo "this is executed from TEST1 stage and branch is master"
							   cat README.md
				               '''
							  }
							}
            stage ( 'TEST2' ) {
		        
					    steps {
				            sh '''
				                echo " this is executed from TEST2 stage and branch is master "
								cat README.md
				               '''
                            }
						}
                    } 
				}
